const SET_ERROR = "SET_ERROR";
const SET_TOKEN = "SET_TOKEN";

const LOGOUT = "LOGOUT";
const SET_AVATAR = "SET_AVATAR";

const SET_ALERT = "SET_ALERT";
const CLOSE_ALERT = "CLOSE_ALERT";

export { SET_TOKEN, SET_ERROR, LOGOUT, SET_AVATAR, SET_ALERT, CLOSE_ALERT };
